### ISSUE TITLE
Remove register change in autoscaling.tf

### ISSUE THREAD

**Issue by Alexys80** [lean-delivery/tf-module-aws-ecs#2]
It would be better not to change register for values of resources names in autoscaling.tf and leave as they are.
The reason is to mitigate risk of naming  inconsistency.

**Comment by ToROxI** [comment]
@Alexys80 please provide use case example when naming inconsistency can be caused by register change.

**Comment by ToROxI** [comment]
@Alexys80 ,
"reporting tool with a case-sensitive search/filter" will search resources via tags, not names. Never the less, you are welcome to create pull request with desired changes.
